SELECT B.BOOK_ID, A.AUTHOR_NAME, date_format(B.PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE ASC

# 다른 풀이
SELECT BOOK_ID, AUTHOR_NAME, 
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK JOIN AUTHOR USING(AUTHOR_ID)
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE

SELECT BOOK_ID, AUTHOR_NAME, date_format(PUBLISHED_DATE,'%Y-%m-%d')
from BOOK b
left join AUTHOR a
on a.AUTHOR_ID = b.AUTHOR_ID
where CATEGORY = "경제"
order by PUBLISHED_DATE asc