SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC



-- DATEDDIFF
-- DATEDDIFF(END_DATE, START_DATE) +1 
-- DATEDDIFF(END_DATE, START_DATE) 이면 DATEDDIFF(2024-05-16, 024-05-16) 일 경우 0이 됨 그래서 +1

-- ROUND 반올림
-- ROUND(숫자, 자릿수) : 자릿수+1 에서 반올림