SELECT D.DEPT_ID , D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY AVG(E.SAL) DESC

-- 반올림
-- ROUND(2.62) -> 3
-- ROUND(2.62, 0) 과 같음
-- 반올림 자릿수
-- ROUND(2.62, 1) -> 2.6

-- 버림
-- TRUNCATE(2.62, 0) -> 2

