SELECT YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    U.GENDER AS GENDER, 
    COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID=O.USER_ID
WHERE U.GENDER = '1' OR U.GENDER = '0'
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE) ASC , MONTH(O.SALES_DATE) ASC , U.GENDER ASC

-- DISTINCT 