WITH
P AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
F AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT
    CASE
        WHEN SKILL_CODE & P.CODE AND SKILL_CODE & F.CODE THEN 'A'
        WHEN SKILL_CODE & C.CODE THEN 'B'
        WHEN SKILL_CODE & F.CODE THEN 'C'
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS, P, C, F
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID