SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(MINUTE, I.DATETIME, O.DATETIME) DESC
LIMIT 2

-- # TIMESTAMPDIFF(단위, 날짜1, 날짜2);
-- # 단위
-- # SECOND : 초
-- # MINUTE : 분
-- # HOUR : 시
-- # DAY : 일
-- # WEEK : 주
-- # MONTH : 월
-- # QUARTER : 분기
-- # YEAR : 연