SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH ,"%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL and DATE_OF_BIRTH LIKE "_____03___" and GENDER="W"
ORDER BY MEMBER_ID