SELECT M.MEMBER_NAME, E.REVIEW_TEXT, DATE_FORMAT(E.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW E ON M.MEMBER_ID=E.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT P.MEMBER_ID
    FROM MEMBER_PROFILE P JOIN REST_REVIEW R ON P.MEMBER_ID=R.MEMBER_ID
    GROUP BY P.MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
    )
ORDER BY E.REVIEW_DATE ASC, E.REVIEW_TEXT ASC