SELECT F.ID AS ID, N.FISH_NAME AS FISH_NAME, F.LENGTH AS LENGTH
FROM FISH_INFO F JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (
    SELECT F.FISH_TYPE, MAX(F.LENGTH)
    FROM FISH_INFO F 
    GROUP BY F.FISH_TYPE
)
ORDER BY F.ID ASC